apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-volume-b
  namespace: cadrart-b
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
