apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cadrart-ingress
  namespace: cadrart
  annotations:
    ingressClassName: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/websocket-services: "backend"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${DOMAIN_NAME}
      secretName: example-tls
  rules:
    - host: ${DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8001
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
          - path: /static
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3000
    - host: db.${DOMAIN_NAME}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: phpmyadmin-service
                port:
                  number: 80
