apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cadrart-logs-pvc
  namespace: cadrart
  labels:
    app: cadrart
    component: logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
