apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
  namespace: cadrart
  labels:
    app: frontend-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    io.kompose.service: frontend-blue
---
apiVersion: v1
kind: Service
metadata:
  name: backend-proxy
  namespace: cadrart
  labels:
    app: backend-proxy
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: api
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: websocket
  selector:
    io.kompose.service: backend-blue
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-prod-proxy
  namespace: cadrart
  labels:
    app: frontend-prod-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: frontend-blue
---
apiVersion: v1
kind: Service
metadata:
  name: backend-prod-proxy
  namespace: cadrart
  labels:
    app: backend-prod-proxy
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 3000
      targetPort: 3000
    - name: websocket
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: backend-blue
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-test-proxy
  namespace: cadrart
  labels:
    app: frontend-test-proxy
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: frontend-green
---
apiVersion: v1
kind: Service
metadata:
  name: backend-test-proxy
  namespace: cadrart
  labels:
    app: backend-test-proxy
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 3000
      targetPort: 3000
    - name: websocket
      port: 8001
      targetPort: 8001
  selector:
    io.kompose.service: backend-green
