apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume-b
  namespace: cadrart-b
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
