apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-volume-a
  namespace: cadrart-a
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
